### ISSUE TITLE
Fact only added when run on command line

### ISSUE THREAD

**Issue by realflash** [GeoffWilliams/geoffwilliams-facter_package_inventory#1]
Geoff,

Thanks for writing this module. It's working great for me on Windows, OS X and Linux when I run the agent on the command line. I get this:

```
Debug: Facter: fact "service_provider" has resolved to "systemd".
Debug: Facter: executing command: /bin/sh -c /opt/puppetlabs/bin/puppet resource package
Debug: Facter: package { 'accountsservice':
  ensure => '0.6.40-2ubuntu11.3',
}
```

all as expected. But  when puppet is running as a service I get this instead:

```
puppet-agent[7560]: (Facter) fact "service_provider" has resolved to "systemd".
puppet-agent[7560]: (Facter) fact "system_packages" resolved to null and will not be added.
```

The service is running as root as was installed using the standard package. Do you have any thoughts?

**Comment by GeoffWilliams** [comment]
@realflash this hasn't been maintained for quite a while. I was just about to deprecate this package on the puppet forge. If your running a recent Puppet Enterprise, the console has built-in support for listing packages now.

That said, I did just try this and it worked as expected, including when run as a service. Since the fact shells out and just runs `puppet resource package`. As a first step, I would make sure that the `puppet` command is in your `PATH` while running the puppet service. On Ubuntu you should be able to set it in `/etc/default/puppet`

**Comment by GeoffWilliams** [comment]
module is deprecated - don't use it
